language: php
sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql
  - postgresql

before_install:
  - travis_retry composer self-update
  - mysql -e 'create database if not exists casbin;'
  - psql -c 'create database casbin;' -U postgres

install:
  - travis_retry composer install --no-suggest --no-interaction

before_script:
  - export XDEBUG_MODE=coverage

script:
 - vendor/bin/phpunit --version
 - mkdir -p build/logs
 - vendor/bin/phpunit

after_script:
 - travis_retry vendor/bin/php-coveralls -v
